import { NextResponse } from 'next/server';
import { Resend } from 'resend';
import { getDriveClient } from '@/lib/sheets';
import { parseStatement } from '@/lib/parsers/index';
import { validateParsedStatement } from '@/lib/parsers/verify';
import { updateCarrierVerificationStatus, INITIAL_CARRIER_ROWS } from '@/lib/carrier-parsers';

export const dynamic = 'force-dynamic';

const SUPPORTED_EXTENSIONS = ['.pdf', '.xls', '.xlsx', '.csv'];

function checkAuth(request) {
  const secret = process.env.CRON_SECRET;
  if (!secret) return true;
  const header = request.headers.get('authorization') || '';
  const fromQuery = new URL(request.url).searchParams.get('secret') || '';
  return header === `Bearer ${secret}` || fromQuery === secret;
}

async function listAllStatementFiles() {
  const folderId = process.env.COMMISSION_DRIVE_FOLDER_ID;
  if (!folderId) throw new Error('COMMISSION_DRIVE_FOLDER_ID env var is required');

  const drive = await getDriveClient();
  const all = [];

  async function listInFolder(id) {
    let pageToken = undefined;
    do {
      const res = await drive.files.list({
        q: `'${id}' in parents and trashed = false`,
        fields: 'nextPageToken, files(id, name, mimeType, modifiedTime, parents)',
        pageSize: 200,
        pageToken,
      });
      for (const f of res.data.files || []) {
        if (f.mimeType === 'application/vnd.google-apps.folder') {
          await listInFolder(f.id);
        } else {
          const lower = (f.name || '').toLowerCase();
          if (SUPPORTED_EXTENSIONS.some(e => lower.endsWith(e))) all.push(f);
        }
      }
      pageToken = res.data.nextPageToken;
    } while (pageToken);
  }

  await listInFolder(folderId);
  return all;
}

async function downloadFile(fileId) {
  const drive = await getDriveClient();
  const res = await drive.files.get({ fileId, alt: 'media' }, { responseType: 'arraybuffer' });
  return Buffer.from(res.data);
}

async function pickAndParseLatestPerCarrier(files) {
  // Sort newest first
  files.sort((a, b) => String(b.modifiedTime).localeCompare(String(a.modifiedTime)));

  // For each file, parse it just enough to detect the carrier.
  // Stop once we've found one for each carrier listed in the sheet.
  const wanted = new Set(INITIAL_CARRIER_ROWS.map(r => r.Carrier));
  const found = new Map(); // carrier name → { file, parsed }

  for (const file of files) {
    if (found.size >= wanted.size) break;
    try {
      const buf = await downloadFile(file.id);
      const parsed = await parseStatement(buf, file.name, null);
      const detected = parsed?.carrier;
      if (!detected) continue;
      // Match against the wanted set by loose comparison
      for (const want of wanted) {
        if (found.has(want)) continue;
        const wlower = want.toLowerCase();
        const dlower = detected.toLowerCase();
        if (wlower.includes(dlower.split(' ')[0]) || dlower.includes(wlower.split(' ')[0])) {
          found.set(want, { file, parsed });
          break;
        }
      }
    } catch (e) {
      // Couldn't parse this one — try the next
      continue;
    }
  }
  return found;
}

async function sendFailureEmail(failures) {
  const apiKey = process.env.RESEND_API_KEY;
  const emailTo = process.env.SUMMARY_EMAIL_TO;
  if (!apiKey || !emailTo) return { sent: false, reason: 'RESEND_API_KEY or SUMMARY_EMAIL_TO not set' };

  const resend = new Resend(apiKey);
  const recipients = emailTo.split(',').map(e => e.trim()).filter(Boolean);
  const fromEmail = process.env.RESEND_FROM || 'TCC Dashboard <onboarding@resend.dev>';

  const html = `
    <h2>🔴 Carrier parser regression detected</h2>
    <p>The nightly parser verification cron found drift in ${failures.length} carrier${failures.length === 1 ? '' : 's'}.</p>
    ${failures.map(f => `
      <h3 style="margin-top:24px">${f.carrier}</h3>
      <p><strong>Tested file:</strong> ${f.fileName || '(no recent file found)'}</p>
      <p><strong>Status:</strong> ${f.status}</p>
      <p><strong>Detail:</strong></p>
      <pre style="background:#f4f4f4;padding:12px;border-radius:4px;font-size:12px;overflow:auto">${f.detail || '(no detail)'}</pre>
    `).join('')}
    <p style="margin-top:32px;color:#666;font-size:11px">
      This alert is generated by /api/cron/verify-parsers.<br/>
      Review the Carrier Parsers tab in the Goals sheet for the full status of each parser.
    </p>
  `;

  const subject = `🔴 TCC parser regression — ${failures.map(f => f.carrier).join(', ')}`;
  const result = await resend.emails.send({ from: fromEmail, to: recipients, subject, html });
  return { sent: true, id: result?.data?.id, error: result?.error };
}

export async function GET(request) {
  if (!checkAuth(request)) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  const ranAt = new Date().toISOString();

  try {
    const files = await listAllStatementFiles();
    const found = await pickAndParseLatestPerCarrier(files);

    const results = [];
    const failures = [];

    for (const row of INITIAL_CARRIER_ROWS) {
      const carrier = row.Carrier;
      const hit = found.get(carrier);

      if (!hit) {
        const status = '✗ no recent statement found in Drive';
        await updateCarrierVerificationStatus(carrier, { status, mismatchDetail: 'No file matching this carrier was found in Drive' });
        results.push({ carrier, ok: false, status });
        failures.push({ carrier, status, detail: 'No file matching this carrier was found in Drive', fileName: null });
        continue;
      }

      const verdict = validateParsedStatement(carrier, hit.parsed);
      const status = verdict.ok ? `✓ ${verdict.summary.replace(/^✓ /, '')}` : `✗ ${verdict.summary.replace(/^✗ /, '')}`;
      const mismatchDetail = verdict.ok
        ? ''
        : verdict.checks.filter(c => !c.ok).map(c => `[${c.name}] ${c.detail}`).join('\n');

      await updateCarrierVerificationStatus(carrier, { status, mismatchDetail });
      results.push({ carrier, ok: verdict.ok, status, file: hit.file.name });
      if (!verdict.ok) failures.push({ carrier, status, detail: mismatchDetail, fileName: hit.file.name });
    }

    let emailResult = null;
    if (failures.length > 0) {
      emailResult = await sendFailureEmail(failures);
    }

    return NextResponse.json({ ok: true, ranAt, totalChecked: results.length, failures: failures.length, results, emailResult });
  } catch (err) {
    return NextResponse.json({ error: err.message, stack: err.stack, ranAt }, { status: 500 });
  }
}
