export const dynamic = 'force-dynamic';
import { fetchSheet } from '@/lib/sheets';
import { parseFlexDate, normalizeCampaign, parseDuration, fuzzyMatchAgent } from '@/lib/utils';
import { NextResponse } from 'next/server';

/**
 * GET /api/crm/lead/[leadId]
 *
 * leadId is either a Lead Id from the dialer or "L-{phone10}" generated by the leads list.
 * Builds lead detail from call logs + sales data directly — no Leads sheet needed.
 */
export async function GET(request, { params }) {
  try {
    const { leadId } = params;

    // Extract phone from leadId if it's our generated format "L-1234567890"
    const isPhoneBased = leadId.startsWith('L-');
    const phone10 = isPhoneBased ? leadId.slice(2) : '';

    const [callsRaw, salesRaw, pricingRaw] = await Promise.all([
      fetchSheet(process.env.CALLLOGS_SHEET_ID, process.env.CALLLOGS_TAB_NAME || 'Report', 120),
      fetchSheet(process.env.SALES_SHEET_ID, process.env.SALES_TAB_NAME || 'Sheet1', 120),
      fetchSheet(process.env.GOALS_SHEET_ID, process.env.GOALS_PRICING_TAB || 'Publisher Pricing', 300),
    ]);

    // Build pricing lookup
    const pricing = {};
    pricingRaw.forEach(r => {
      const code = (r['Campaign Code'] || '').trim();
      if (!code || (r['Status'] || '').trim() === 'Inactive') return;
      pricing[code] = {
        buffer: parseInt(r['Buffer (seconds)'] || r['Buffer'] || '0') || 0,
      };
    });

    const allAgentNames = [...new Set(salesRaw.map(r => r['Agent']?.trim()).filter(Boolean))];

    // Find matching calls — by Lead Id or by phone
    const matchingCalls = callsRaw.filter(r => {
      if (!isPhoneBased) {
        // Match by dialer Lead Id
        const rowLeadId = (r['Lead Id'] || '').toString().trim();
        return rowLeadId === leadId;
      }
      // Match by phone
      const rowPhone = String(r['Phone'] || r['Phone Number'] || '').replace(/\.0$/, '').replace(/[^0-9]/g, '').slice(-10);
      return rowPhone === phone10;
    });

    if (matchingCalls.length === 0) {
      return NextResponse.json({ error: 'Lead not found — no matching calls' }, { status: 404 });
    }

    // Build enriched call list
    const recentCalls = matchingCalls
      .map(c => {
        const rawCampaign = c['Campaign']?.trim() || '';
        const normalized = normalizeCampaign(rawCampaign);
        const priceInfo = pricing[normalized] || {};
        const callDuration = parseDuration(c['Duration']);
        const callTypeRaw = (c['Call Type'] || '').trim().toLowerCase();
        const overrideRaw = (c['Billable Override'] || '').trim().toUpperCase();
        const computedBillable = callTypeRaw === 'inbound' && callDuration > (priceInfo.buffer || 0);
        const isBillable = overrideRaw === 'N' ? false : overrideRaw === 'Y' ? true : computedBillable;

        return {
          date: parseFlexDate(c['Date']) || '',
          rep: fuzzyMatchAgent(c['Rep']?.trim() || '', allAgentNames),
          campaign: rawCampaign,
          subcampaign: c['Subcampaign']?.trim() || '',
          duration: callDuration,
          callStatus: c['Standardized Call Status']?.trim() || c['Call Status']?.trim() || '',
          callType: c['Call Type']?.trim() || '',
          isBillable,
          state: c['State']?.trim() || '',
          phone: c['Phone']?.trim() || '',
          hangup: c['Hangup']?.trim() || '',
          hangupSource: c['Hangup Source']?.trim() || '',
          holdTime: parseInt(c['HoldTime']) || 0,
          inboundSource: c['Inbound Source']?.trim() || '',
          recording: c['Recording']?.trim() || '',
          details: c['Details']?.trim() || '',
          leadId: c['Lead Id']?.trim() || '',
          attempt: parseInt(c['Attempt']) || 0,
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date));

    // Derive lead info from calls
    const callPhone = phone10 || String(matchingCalls[0]['Phone'] || '').replace(/[^0-9]/g, '').slice(-10);
    const firstName = matchingCalls.find(c => c['First']?.trim())?.['First']?.trim() || '';
    const lastName = matchingCalls.find(c => c['Last']?.trim())?.['Last']?.trim() || '';

    // Count agents
    const agentCounts = {};
    recentCalls.forEach(c => { if (c.rep) agentCounts[c.rep] = (agentCounts[c.rep] || 0) + 1; });
    const primaryAgent = Object.entries(agentCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || '';

    const campaigns = [...new Set(recentCalls.map(c => c.campaign).filter(Boolean))];
    const billableCount = recentCalls.filter(c => c.isBillable).length;
    const latestDate = recentCalls[0]?.date || '';
    const earliestDate = recentCalls[recentCalls.length - 1]?.date || '';
    const state = recentCalls.find(c => c.state)?.state || '';

    // Cross-reference with sales by phone
    const policies = salesRaw
      .filter(r => {
        const sPhone = (r['Phone Number'] || '').replace(/[^0-9]/g, '').slice(-10);
        return sPhone === callPhone;
      })
      .map(r => {
        const carrierProductPayout = r['Carrier + Product + Payout'] || '';
        const parts = carrierProductPayout.split(',').map(s => s.trim());
        return {
          policyNumber: r['Policy #']?.trim() || '',
          carrier: parts[0] || '',
          product: parts[1] || '',
          effectiveDate: parseFlexDate(r['Effective Date']) || '',
          status: r['Placed?']?.trim() || '',
          premium: parseFloat(r['Monthly Premium']) || 0,
          faceAmount: parseFloat(r['Face Amount']) || 0,
          termLength: r['Term Length']?.trim() || '',
          paymentType: r['Payment Type']?.trim() || '',
          paymentFrequency: r['Payment Frequency']?.trim() || '',
          outcome: r['Outcome at Application Submission']?.trim() || '',
          salesNotes: r['Sales Notes']?.trim() || '',
          submissionDate: parseFlexDate(r['Application Submitted Date']) || '',
          agent: r['Agent']?.trim() || '',
        };
      });

    // Build applicant from sales data
    let applicant = null;
    const salesRow = salesRaw.find(r => {
      const sPhone = (r['Phone Number'] || '').replace(/[^0-9]/g, '').slice(-10);
      return sPhone === callPhone;
    });
    if (salesRow) {
      applicant = {
        firstName: salesRow['First Name']?.trim() || '',
        lastName: salesRow['Last Name']?.trim() || '',
        gender: salesRow['Gender']?.trim() || '',
        dob: salesRow['Date of Birth']?.trim() || '',
        email: salesRow['Email Address']?.trim() || '',
        phone: salesRow['Phone Number']?.trim() || '',
        address: salesRow['Street Address']?.trim() || '',
        city: salesRow['City']?.trim() || '',
        state: salesRow['State']?.trim() || '',
        zip: salesRow['Zip Code']?.trim() || '',
        textFriendly: salesRow['Text Friendly']?.trim() || '',
        ssnMatch: salesRow['Social Security Billing Match']?.trim() || '',
      };
    }

    // Determine status from most recent call's Call Status, override if placed
    const hasPlaced = policies.some(p => ['Advance Released', 'Active - In Force', 'Submitted - Pending'].includes(p.status));
    const latestCallStatus = recentCalls[0]?.callStatus || 'UNKNOWN';
    let leadStatus = hasPlaced ? 'CONVERTED' : latestCallStatus;

    // Build name — prefer sales, fall back to call logs
    let name = '';
    if (applicant && applicant.firstName) {
      name = [applicant.firstName, applicant.lastName].filter(Boolean).join(' ');
    } else {
      name = [firstName, lastName].filter(Boolean).join(' ') || 'Unknown';
    }

    return NextResponse.json({
      leadId,
      phone: formatPhone(callPhone),
      name,
      firstName: name.split(' ')[0] || '',
      lastName: name.split(' ').slice(1).join(' ') || '',
      source: campaigns[0] || '',
      agent: primaryAgent,
      status: leadStatus,
      createdAt: earliestDate,
      lastContact: latestDate,
      followUpDue: '',
      attempts: recentCalls.length,
      billableCalls: billableCount,
      notes: '',
      tags: '',
      doNotCall: false,
      policyNumber: policies[0]?.policyNumber || '',
      state,
      // Enriched data
      recentCalls,
      policy: policies[0] || null,
      applicant,
      convertedPolicies: policies,
    });
  } catch (error) {
    console.error('[crm/lead] GET error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

function formatPhone(digits) {
  if (digits.length === 10) return `(${digits.slice(0,3)}) ${digits.slice(3,6)}-${digits.slice(6)}`;
  if (digits.length === 11) return `(${digits.slice(1,4)}) ${digits.slice(4,7)}-${digits.slice(7)}`;
  return digits;
}
